USE [master]
GO

/****** Object:  Database [GatewayUserDB]    Script Date: 2020-12-21 23:39:34 ******/
DROP DATABASE [GatewayUserDB]
GO

/****** Object:  Database [GatewayUserDB]    Script Date: 2020-12-21 23:39:34 ******/
CREATE DATABASE [GatewayUserDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GatewayUserDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GatewayUserDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GatewayUserDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GatewayUserDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GatewayUserDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GatewayUserDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GatewayUserDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GatewayUserDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GatewayUserDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GatewayUserDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GatewayUserDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GatewayUserDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GatewayUserDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GatewayUserDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GatewayUserDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GatewayUserDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GatewayUserDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GatewayUserDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GatewayUserDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GatewayUserDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GatewayUserDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GatewayUserDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GatewayUserDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GatewayUserDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GatewayUserDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GatewayUserDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GatewayUserDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GatewayUserDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GatewayUserDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GatewayUserDB] SET  MULTI_USER 
GO

ALTER DATABASE [GatewayUserDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GatewayUserDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GatewayUserDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GatewayUserDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GatewayUserDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GatewayUserDB] SET  READ_WRITE 
GO

